# Default values for compass-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.repo1.uhc.com/yourOrg/KEBAB_NAME
  tag: sentFromBuild
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 8080
  containerPort: 8080 # should not need to change

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: angular-boot.optum.com
      paths:
        - /

  tls:
    - secretName: angularbootcert
      hosts:
        - angular-boot.optum.com

resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

compass: {}
